package mx.uaemex.model;
// Generated 26-nov-2015 11:12:29 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     private Integer numFactura;
     private Date fecha;
     private Float subtotal;
     private Float iva;
     private Float total;
     private int idCliente;

    public Factura() {
    }

	
    public Factura(int idCliente) {
        this.idCliente = idCliente;
    }
    public Factura(Date fecha, Float subtotal, Float iva, Float total, int idCliente) {
       this.fecha = fecha;
       this.subtotal = subtotal;
       this.iva = iva;
       this.total = total;
       this.idCliente = idCliente;
    }
   
    public Integer getNumFactura() {
        return this.numFactura;
    }
    
    public void setNumFactura(Integer numFactura) {
        this.numFactura = numFactura;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Float getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(Float subtotal) {
        this.subtotal = subtotal;
    }
    public Float getIva() {
        return this.iva;
    }
    
    public void setIva(Float iva) {
        this.iva = iva;
    }
    public Float getTotal() {
        return this.total;
    }
    
    public void setTotal(Float total) {
        this.total = total;
    }
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }




}


